defmodule PhxTestServerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :phx_test_server

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_phx_test_server_key",
    signing_salt: "X/aFHTmY",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # WebSocket for Go client testing (JSON)
  socket "/socket", PhxTestServerWeb.UserSocket,
    websocket: true,
    longpoll: false

  # WebSocket for Go client testing (Binary)
  socket "/binary_socket", PhxTestServerWeb.BinarySocket,
    websocket: [serializer: [{Phoenix.Socket.V1.BinarySerializer, "~> 1.0.0"}]],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :phx_test_server,
    gzip: not code_reloading?,
    only: PhxTestServerWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PhxTestServerWeb.Router
end
